# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Gregory Hunter Goodreau'
#tagline:          'Gregory Hunter Goodreau'
description:      'Computer science student and software developer'
url:              http://ghgoodreau.github.io
baseurl:          /

author:
  name:           'Gregory Goodreau'
  url:            ghgoodreau.github.io
  email:          'ghg0004@auburn.edu'
  github:         'https://github.com/ghgoodreau'
  twitter:        'https://twitter.com/ghgoodreau'
  linkedin:       'https://www.linkedin.com/in/ghgoodreau'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
