# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Gregory Hunter Goodreau'
tagline:          'Gregory Hunter Goodreau'
description:      'Computer science student and software developer'
url:              http://ghgoodreau.github.io
baseurl:          '/hyde/'

author:
  name:           'Gregory Goodreau'
  url:            https://twitter.com/ghgoodreau

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
